

export const stockViewColumnBluePrint = [

  {
    key: 'itemId',
    humanReadable: 'ID',
    align: 'left',
    visable: false,
    type: 'number',
    primaryKey: true,
    allowGrouping: true,
    editable: false,
    allowFiltering: false,
    width: '20px',
    isIdentity: true,
    format: ''
  },
  {
    key: 'itemCode',
    humanReadable: 'Code',
    align: 'left',
    visable: true,
    type: 'string',
    primaryKey: false,
    allowGrouping: false,
    allowFiltering: true,
    editable: false,
    width: '30px',
    isIdentity: false,
    format: ''
  },
  {
    key: 'itemName',
    humanReadable: 'Description',
    align: 'left',
    visable: true,
    type: 'string',
    allowFiltering: true,
    primaryKey: false,
    allowGrouping: false,
    editable: false,
    width: '40',
    isIdentity: false,
    format: ''
  },
  {
    key: 'inStock',
    humanReadable: 'In Stock',
    align: 'left',
    visable: true,
    type: 'number',
    allowFiltering: true,
    primaryKey: false,
    allowGrouping: true,
    editable: false,
    width: '30',
    isIdentity: false,

  },
  {
    key: 'available',
    humanReadable: 'Available',
    align: 'left',
    visable: true,
    type: 'number',
    allowFiltering: true,
    primaryKey: false,
    allowGrouping: true,
    editable: false,
    width: '30',
    isIdentity: false,

  },
  {
    key: 'booked',
    humanReadable: 'Booked',
    align: 'left',
    visable: true,
    type: 'number',
    allowFiltering: true,
    primaryKey: false,
    allowGrouping: true,
    editable: false,
    width: '30',
    isIdentity: false
  },
  {
    key: 'totalExpected',
    humanReadable: 'Total Expected',
    align: 'left',
    visable: true,
    type: 'number',
    allowFiltering: true,
    primaryKey: false,
    allowGrouping: true,
    editable: false,
    width: '30',
    isIdentity: false
  },
  {
    key: 'expectedAvailable',
    humanReadable: 'Expected Available',
    align: 'left',
    visable: true,
    type: 'number',
    allowFiltering: true,
    primaryKey: false,
    allowGrouping: true,
    editable: false,
    width: '30',
    isIdentity: false
  },
  {
    key: 'expectedBooked',
    humanReadable: 'Expected Booked',
    align: 'left',
    visable: true,
    type: 'number',
    allowFiltering: true,
    primaryKey: false,
    allowGrouping: true,
    editable: false,
    width: '30',
    isIdentity: false
  },
  {
    key: 'averageCost',
    humanReadable: 'Avg. Cost',
    align: 'left',
    visable: true,
    type: 'number',
    allowFiltering: true,
    primaryKey: false,
    allowGrouping: true,
    editable: false,
    width: '30',
    isIdentity: false,
    format: 'C2'
  },
  {
    key: 'totalCost',
    humanReadable: 'Total Cost',
    align: 'left',
    visable: true,
    type: 'number',
    allowFiltering: true,
    primaryKey: false,
    allowGrouping: true,
    editable: false,
    width: '30',
    isIdentity: false,
    format: 'C2'
  }
];
